### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by machta** [PrinceDhaliwal/jast#2]
I used the new version and there are some parsing problems similar to the ones before. I will just post here the cases that failed. Every line is one test case.
``` js
var a = 5; ++a*2;
var a = 5; var c = --a*2; a*c;
var a = false; a = !a; a;
var x = 6, y = 3; !(x == y);
~5;
~(-6);
~-6;
```

And this gives undefined reference compilation error. 
``` c++
jast::Tokenizer lex(&scanner);
lex.reset(&scanner);
```
You forgot to define that reset function...

**Comment by DhaliwalX** [comment]
I have fixed the undefined reference error. I am looking for parsing errors as you have mentioned.

**Comment by machta** [comment]
Thanks. Looks like it works. Good job 👍
